# -------------------------------------------------
# Kalibr Dockerfile for Jetson (ARM64/aarch64)
# -------------------------------------------------
FROM dustynv/ros:noetic-ros-base-l4t-r35.4.1

ENV DEBIAN_FRONTEND=noninteractive

# -----------------------------------------------------------------
# 1) Refresh the ROS GPG key (the base image's key may be expired)
# -----------------------------------------------------------------
RUN apt-get update || true && \
    apt-get install -y curl && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------------------
# 2) Install libffi8 from Ubuntu 22.04 (required by NVIDIA libraries)
# -----------------------------------------------------------------
RUN cd /tmp && \
    wget http://ports.ubuntu.com/pool/main/libf/libffi/libffi8_3.4.2-4_arm64.deb && \
    dpkg -i libffi8_3.4.2-4_arm64.deb && \
    rm libffi8_3.4.2-4_arm64.deb && \
    ldconfig

# -----------------------------------------------------------------
# 3) Install the ROS packages Kalibr needs
#    (cv_bridge is omitted - we'll build it from source)
# -----------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    git wget autoconf automake nano \
    python3-dev python3-pip python3-numpy python3-scipy python3-matplotlib \
    ipython3 python3-tk python3-igraph python3-pyx \
    libeigen3-dev libboost-all-dev libsuitesparse-dev \
    doxygen \
    libpoco-dev libtbb-dev libblas-dev liblapack-dev libv4l-dev \
    python3-catkin-tools python3-osrf-pycommon \
    ros-noetic-rosbag ros-noetic-image-transport \
    ros-noetic-tf ros-noetic-rospy ros-noetic-roscpp \
    libffi-dev && \
    rm -rf /var/lib/apt/lists/*

# -----------------------------------------------------------------
# 4) Install wxPython (used by Kalibr's GUI)
# -----------------------------------------------------------------
RUN apt-get update && apt-get install -y python3-wxgtk4.0 || \
    pip3 install wxPython || echo "wxPython optional, continuing..."

# -----------------------------------------------------------------
# 4b) Upgrade scipy (fixes numpy.typeDict compatibility error)
# -----------------------------------------------------------------
RUN pip3 install --upgrade scipy

# -----------------------------------------------------------------
# 5) Make the numpy headers visible to the compiler
# -----------------------------------------------------------------
RUN NUMPY_INCLUDE=$(python3 -c "import numpy; print(numpy.get_include())") && \
    ln -sf ${NUMPY_INCLUDE}/numpy /usr/include/numpy

# -----------------------------------------------------------------
# 6) Create the catkin workspace
# -----------------------------------------------------------------
ENV WORKSPACE=/catkin_ws
RUN mkdir -p $WORKSPACE/src && \
    cd $WORKSPACE && \
    catkin init && \
    catkin config --extend /opt/ros/noetic && \
    catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release

# -----------------------------------------------------------------
# 7) Clone cv_bridge from source (to avoid libopencv-dev conflict)
# -----------------------------------------------------------------
RUN cd $WORKSPACE/src && \
    git clone https://github.com/ros-perception/vision_opencv.git -b noetic

# -----------------------------------------------------------------
# 8) Copy the Kalibr source code into the workspace
# -----------------------------------------------------------------
ADD . $WORKSPACE/src/kalibr

# -----------------------------------------------------------------
# 9) Build everything (use only 2 parallel jobs - Jetson has 8 GB RAM)
# -----------------------------------------------------------------
RUN cd $WORKSPACE && catkin build -j2

# -----------------------------------------------------------------
# 10) Set up the entrypoint
# -----------------------------------------------------------------
ENV KALIBR_MANUAL_FOCAL_LENGTH_INIT=1
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["bash", "-c", "source /catkin_ws/devel/setup.bash && cd /catkin_ws && exec bash"]
